// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARCavQXN3-cd4oQqFFoRySehWY1kxMRCU',
    appId: '1:909052817190:ios:f14d3aa35f58f926591be7',
    messagingSenderId: '909052817190',
    projectId: 'bloc-ecommerce-e660',
    storageBucket: 'bloc-ecommerce-e660.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARCavQXN3-cd4oQqFFoRySehWY1kxMRCU',
    appId: '1:909052817190:ios:f14d3aa35f58f926591be7',
    messagingSenderId: '909052817190',
    projectId: 'bloc-ecommerce-e660',
    storageBucket: 'bloc-ecommerce-e660.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd-YAuXH4kZhsw5G8zrAIk2KsmSrw4mQc',
    appId: '1:909052817190:web:e869530a80ca9422591be7',
    messagingSenderId: '909052817190',
    projectId: 'bloc-ecommerce-e660',
    authDomain: 'bloc-ecommerce-e660.firebaseapp.com',
    storageBucket: 'bloc-ecommerce-e660.firebasestorage.app',
    measurementId: 'G-PPZ4XZL1Y8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-YAuXH4kZhsw5G8zrAIk2KsmSrw4mQc',
    appId: '1:909052817190:web:e869530a80ca9422591be7',
    messagingSenderId: '909052817190',
    projectId: 'bloc-ecommerce-e660',
    authDomain: 'bloc-ecommerce-e660.firebaseapp.com',
    storageBucket: 'bloc-ecommerce-e660.firebasestorage.app',
    measurementId: 'G-PPZ4XZL1Y8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqlEz2Ucx68CgqL7HgMZZMMTh0_tMNUNo',
    appId: '1:909052817190:android:0b0fe2d949fd6b6a591be7',
    messagingSenderId: '909052817190',
    projectId: 'bloc-ecommerce-e660',
    storageBucket: 'bloc-ecommerce-e660.firebasestorage.app',
  );

}